require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ReactNativeAppsflyer' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ReactNativeAppsflyerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  post_install do |installer|
  # Disable Flipper due to XCode 12.5.1 error: https://github.com/react-native-community/upgrade-support/issues/155
  #    flipper_post_install(installer)

  # Below are attempts to fix build error to device in XCode
  # Attempt 1: ONLY_ACTIVE_ARCH = 'YES' - https://developer.apple.com/forums/thread/656509?answerId=626387022#626387022
  #     installer.pods_project.targets.each do |target|
  #       target.build_configurations.each do |config|
  #         config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
  #       end
  #     end

  # Attempt 2: Ignore arm64 - https://stackoverflow.com/a/63955114
  #     installer.pods_project.build_configurations.each do |config|
  #       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  #     end
  end
end

target 'ReactNativeAppsflyer-tvOS' do
  # Pods for ReactNativeAppsflyer-tvOS

  target 'ReactNativeAppsflyer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
